In [2]:
import pandas as pd
import scipy

In [5]:
pwd

'C:\\Users\\patry\\Desktop\\technopol-ai'

In [10]:
df = pd.read_csv('data/train_data.csv', error_bad_lines = False)

C:\Users\patry\AppData\Local\Temp\ipykernel_21996\2705250927.py:1: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv('data/train_data.csv', error_bad_lines = False)
b'Skipping line 5856: expected 40 fields, saw 70\nSkipping line 7939: expected 40 fields, saw 49\n'


In [11]:
df

BBLE  BORO  BLOCK   LOT EASEMENT                OWNER BLDGCL  \
0      1001791101     1    179  1101      NaN  155 FRANKLIN ST LLC     RK   
1      1000163436     1     16  3436      NaN         BROADLAR LLC     R4   
2      1000761255     1     76  1255      NaN         HAM, RICHARD     R4   
3      1000161179     1     16  1179      NaN        SHIM, HAE JIN     R4   
4      1001751526     1    175  1526      NaN        BRIT GIRL LLC     R4   
...           ...   ...    ...   ...      ...                  ...    ...   
11941  5016700045     5   1670    45      NaN       MORGAN, DONALD     A5   
11942  5016911023     5   1691  1023      NaN     THOMPSON, NICOLA     R3   
11943  5016960050     5   1696    50      NaN     GREGORY E MCNEIL     A2   
11944  5019850130     5   1985   130      NaN           PAUL ADEST     A5   
11945  5019800044     5   1980    44      NaN         HERTZ, BARRY     B2   

      TAXCLASS  LTFRONT  LTDEPTH  ... VALTYPE    Borough   Latitude  \
0            4        0        0  ...   AC-TR  MANHATTAN  40.719232   
1            2        0        0  ...   AC-TR  MANHATTAN  40.709270   
2            2        0        0  ...   AC-TR  MANHATTAN  40.708006   
3            2        0        0  ...   AC-TR  MANHATTAN  40.709506   
4            2        0        0  ...   AC-TR  MANHATTAN  40.718024   
...        ...      ...      ...  ...     ...        ...        ...   
11941        1       25      100  ...   AC-TR  STATEN IS  40.625493   
11942       1A        0        0  ...   AC-TR  STATEN IS  40.625612   
11943        1       45      100  ...   AC-TR  STATEN IS  40.624666   
11944        1       62       50  ...   AC-TR  STATEN IS  40.599127   
11945        1       47      100  ...   AC-TR  STATEN IS  40.600054   

       Longitude  Community Board  Council District  Census Tract  \
0     -74.008095            101.0               1.0          33.0   
1     -74.016487            101.0               1.0       31704.0   
2     -74.006164            101.0               1.0        1502.0   
3     -74.018002            101.0               1.0       31704.0   
4     -74.003903            101.0               1.0          33.0   
...          ...              ...               ...           ...   
11941 -74.166429            501.0              49.0       30302.0   
11942 -74.159455            501.0              49.0       30302.0   
11943 -74.155115            501.0              49.0       30302.0   
11944 -74.134083            502.0              50.0       27302.0   
11945 -74.139501            502.0              50.0       27302.0   

                BIN                                                NTA  \
0      1.002013e+06             SoHo-TriBeCa-Civic Center-Little Italy   
1      1.000053e+06                  Battery Park City-Lower Manhattan   
2      1.087867e+06                  Battery Park City-Lower Manhattan   
3      1.000061e+06                  Battery Park City-Lower Manhattan   
4      1.001937e+06             SoHo-TriBeCa-Civic Center-Little Italy   
...             ...                                                ...   
11941  5.151984e+06  Mariner's Harbor-Arlington-Port Ivory-Granitev...   
11942  5.118625e+06  Mariner's Harbor-Arlington-Port Ivory-Granitev...   
11943  5.033624e+06  Mariner's Harbor-Arlington-Port Ivory-Granitev...   
11944  5.034388e+06                  New Springville-Bloomfield-Travis   
11945  5.034204e+09                  New Springville-Bloomfield-Travis   

           New Georeferenced Column  
0      POINT (-74.008095 40.719232)  
1       POINT (-74.016487 40.70927)  
2      POINT (-74.006164 40.708006)  
3      POINT (-74.018002 40.709506)  
4      POINT (-74.003903 40.718024)  
...                             ...  
11941  POINT (-74.166429 40.625493)  
11942  POINT (-74.159455 40.625612)  
11943  POINT (-74.155115 40.624666)  
11944  POINT (-74.134083 40.599127)  
11945  POINT (-74.139501 40.600054)  

[11946 rows x 40 columns]

In [13]:
categorical_data = df[['BORO', 'BLOCK', 'LOT', 'EASEMENT', 'BLDGCL', 'TAXCLASS', 'EXT', 'STADDR', 'POSTCODE', 'EXMPTCL', 'EXCD2', 'YEAR', 'VALTYPE', 'Community Board', 'Council District', 'Census Tract', 'BIN', 'NTA', ]]

In [16]:
continuos_data = df [['FULLVAL','LTFRONT', 'LTDEPTH', 'STORIES', 'AVLAND', 'AVTOT', 'EXLAND', 'EXTOT', 'BLDFRONT', 'BLDDEPTH', 'AVLAND2', 'AVTOT2', 'EXLAND2', 'EXTOT2', 'Latitude', 'Longitude' ]]

In [ ]:
predicted_data = df [['FULLVAL']]

In [19]:
correlation = continuos_data.corr(method="pearson");

In [117]:
correlation['FULLVAL']

FULLVAL      1.000000
LTFRONT      0.300811
LTDEPTH      0.199380
STORIES      0.085177
AVLAND       0.732218
AVTOT        0.995879
EXLAND       0.457002
EXTOT        0.595882
BLDFRONT     0.216480
BLDDEPTH     0.275971
AVLAND2      0.729220
AVTOT2       0.997733
EXLAND2      0.766172
EXTOT2       0.981573
Latitude     0.034309
Longitude    0.008063
Name: FULLVAL, dtype: float64

In [118]:
correlation['FULLVAL'][correlation['FULLVAL'].sum(1) > 0.7 ]

ValueError: No axis named 1 for object type Series

In [26]:
continuos_data[continuos_data['AVTOT'] == 0]

FULLVAL  LTFRONT  LTDEPTH  STORIES  AVLAND  AVTOT  EXLAND  EXTOT  \
47           0        0        0      6.0       0      0       0      0   
59           0       24      100      6.0       0      0       0      0   
100          0      248      120     66.0       0      0       0      0   
155          0      174      103      9.0       0      0       0      0   
211          0       42       98     12.0       0      0       0      0   
...        ...      ...      ...      ...     ...    ...     ...    ...   
11553        0        0        0      NaN       0      0       0      0   
11559        0       10      228      NaN       0      0       0      0   
11700        0      278      190      NaN       0      0       0      0   
11839        0       30      271      NaN       0      0       0      0   
11934        0      106      248      3.0       0      0       0      0   

       BLDFRONT  BLDDEPTH  AVLAND2  AVTOT2  EXLAND2  EXTOT2   Latitude  \
47            0         0      NaN     NaN      NaN     NaN  40.717247   
59           25        95      NaN     NaN      NaN     NaN  40.721027   
100         248       120      NaN     NaN      NaN     NaN  40.706400   
155           0         0      NaN     NaN      NaN     NaN  40.708921   
211          42        94      NaN     NaN      NaN     NaN  40.706732   
...         ...       ...      ...     ...      ...     ...        ...   
11553         0         0      NaN     NaN      NaN     NaN        NaN   
11559         0         0      NaN     NaN      NaN     NaN        NaN   
11700         0         0      NaN     NaN      NaN     NaN  40.624179   
11839         0         0      NaN     NaN      NaN     NaN        NaN   
11934         0         0      NaN     NaN      NaN     NaN  40.580737   

       Longitude  
47    -73.999170  
59    -74.004881  
100   -74.008043  
155   -74.016505  
211   -74.008620  
...          ...  
11553        NaN  
11559        NaN  
11700 -74.154202  
11839        NaN  
11934 -74.162094  

[226 rows x 16 columns]

In [31]:
df['BORO'].unique()

array([1, 2, 3, 4, 5], dtype=int64)

In [37]:
from scipy import stats

F, p = stats.f_oneway(df[df.BORO==1].FULLVAL,
                      df[df.BORO==2].FULLVAL,
                      df[df.BORO==3].FULLVAL,
                     df[df.BORO==4].FULLVAL,
                     df[df.BORO==5].FULLVAL)

In [40]:
F

25.057893823867328

In [60]:
from sklearn.linear_model import LinearRegression
import numpy as np

In [44]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(df, test_size=0.2)

In [100]:
reg = LinearRegression().fit(df[['AVTOT']], df[['FULLVAL']])

In [101]:
reg.score(train[['AVTOT']], train[['FULLVAL']])

0.9917149008272769

In [102]:
reg.coef_

array([[2.21463198]])

In [103]:
reg.intercept_

array([425749.43516321])

In [104]:
predicted = reg.predict(test[['AVTOT']])

In [105]:
diff = predicted - test[['FULLVAL']]

In [106]:
predicted

array([[ 484747.23121864],
       [ 478687.99811024],
       [ 494779.51410644],
       ...,
       [1017049.53101201],
       [2675040.40977655],
       [ 663545.54445195]])

array([487330.26021393])

In [107]:
test[['FULLVAL']]

FULLVAL
8957    444000
2000    551000
6165    535000
4414    111631
3133     80292
...        ...
10275   561000
4622   1050000
35      593327
2103   2257000
1634    238610

[2390 rows x 1 columns]

In [108]:
df_test = test[['FULLVAL', 'AVTOT']]

In [109]:
df_test

FULLVAL    AVTOT
8957    444000    26640
2000    551000    23904
6165    535000    31170
4414    111631    50234
3133     80292    36131
...        ...      ...
10275   561000    31164
4622   1050000    75296
35      593327   266997
2103   2257000  1015650
1634    238610   107375

[2390 rows x 2 columns]

In [82]:
def ooo(pred) :
    print('row')
    print(pred)

In [115]:
with np.printoptions(precision=3, suppress=True):
    df_test['pred'] = df_test.apply(lambda row: reg.predict(np.array([row['AVTOT']]).reshape(1, -1))[0][0] , axis=1)

C:\Users\patry\miniconda3\envs\pakmany2\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\patry\miniconda3\envs\pakmany2\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\patry\miniconda3\envs\pakmany2\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\patry\miniconda3\envs\pakmany2\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\patry\miniconda3\envs\pakmany2\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\patry\

C:\Users\patry\miniconda3\envs\pakmany2\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\patry\miniconda3\envs\pakmany2\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\patry\miniconda3\envs\pakmany2\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\patry\miniconda3\envs\pakmany2\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\patry\miniconda3\envs\pakmany2\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\patry\

In [114]:
df_test['diff'] = (df_test['FULLVAL'] - df_test['pred'])/df_test['FULLVAL']

C:\Users\patry\AppData\Local\Temp\ipykernel_21996\3061479279.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['diff'] = (df_test['FULLVAL'] - df_test['pred'])/df_test['FULLVAL']


In [116]:
df_test

FULLVAL    AVTOT          pred      diff
8957    444000    26640  4.847472e+05 -0.091773
2000    551000    23904  4.786880e+05  0.131238
6165    535000    31170  4.947795e+05  0.075178
4414    111631    50234  5.369993e+05 -3.810485
3133     80292    36131  5.057663e+05 -5.299087
...        ...      ...           ...       ...
10275   561000    31164  4.947662e+05  0.118064
4622   1050000    75296  5.925024e+05  0.435712
35      593327   266997  1.017050e+06 -0.714147
2103   2257000  1015650  2.675040e+06 -0.185219
1634    238610   107375  6.635455e+05 -1.780879

[2390 rows x 4 columns]

In [113]:
df_test

FULLVAL    AVTOT          pred      diff
8957    444000    26640  4.847472e+05 -0.091773
2000    551000    23904  4.786880e+05  0.131238
6165    535000    31170  4.947795e+05  0.075178
4414    111631    50234  5.369993e+05 -3.810485
3133     80292    36131  5.057663e+05 -5.299087
...        ...      ...           ...       ...
10275   561000    31164  4.947662e+05  0.118064
4622   1050000    75296  5.925024e+05  0.435712
35      593327   266997  1.017050e+06 -0.714147
2103   2257000  1015650  2.675040e+06 -0.185219
1634    238610   107375  6.635455e+05 -1.780879

[2390 rows x 4 columns]

In [97]:
df_test['diff'] = (df_test['FULLVAL'] - df_test['pred'])

C:\Users\patry\AppData\Local\Temp\ipykernel_21996\2221458647.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['diff'] = (df_test['FULLVAL'] - df_test['pred'])


In [98]:
df_test

FULLVAL    AVTOT          pred           diff
8957    444000    26640  4.873303e+05  -43330.260214
2000    551000    23904  4.812735e+05   69726.458093
6165    535000    31170  4.973584e+05   37641.620660
4414    111631    50234  5.395606e+05 -427929.600756
3133     80292    36131  5.083406e+05 -428048.608696
...        ...      ...           ...            ...
10275   561000    31164  4.973451e+05   63654.902937
4622   1050000    75296  5.950407e+05  454959.328265
35      593327   266997  1.019412e+06 -426084.635211
2103   2257000  1015650  2.676714e+06 -419714.387515
1634    238610   107375  6.660544e+05 -427444.365650

[2390 rows x 4 columns]

In [126]:
continuos_data_1 = continuos_data[[]]

NameError: name 'df_continous' is not defined